### PR TITLE
Fix EZP-23171: delete() must accept arrays

### PR DESCRIPTION
**Pull request by bdunogier**
> See ezsystems/ezdfs-fsbackend-dispatcher#4
> JIRA: https://jira.ez.no/browse/EZP-23171

## TODO
- [ ] Test bulk delete

### CODE REVIEW

**Comment by bdunogier** [comment]
Ping @andrerom @lolautruche :-)

**Comment by lolautruche** [comment]
+1

**Comment by andrerom** [comment]
+1 (no bulk support?)

**Comment by bdunogier** [comment]
Good point, @andrerom. There is of course [an API for that](http://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingMultipleObjectsUsingPHPSDK.html).

**Comment by bdunogier** [comment]
Added bulk delete, untested.

**Comment by andrerom** [comment]
still +1 (but should probably be tested ;) )

**Comment by bdunogier** [comment]
Probably :)

**Comment by andrerom** [comment]
@bdunogier relevant for 2.0-beta as well perhaps?

**Pull request closed without merging**
